### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by idastorm** [idastorm/practice#5]
Suggestion @johaahlf – no symbol needed for ” Road or coastal station”: we make it red to match the roads and the text will show up text to the road-line-feature.

**Comment by johaahlf** [comment]
#5 But the road-line feature has a long extent, the road station is a point which is not always attached to a line.

**Comment by idastorm** [comment]
Aha, good point!

**Comment by idastorm** [comment]
solves issue #5

**Comment by idastorm** [comment]
Fixes #5
